### ISSUE TITLE
Lecture 3.1 data processing pangeo - Kernel died

### ISSUE THREAD

**Issue by jonas-eberle** [EO-College/cubes-and-clouds#89]
I have tried lecture 3.1: https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/3.1_data_processing/3.1_exercises/_alternatives/31_data_processing_pangeo.ipynb

Using the "Cubes&Clouds" environment (4 GB RAM), the kernel died in the part of the visualization (see screenshot). Seems to be an issue with to limited RAM (?).

![Image](https://github.com/user-attachments/assets/6a97242f-3678-4f6b-a50c-1c28cac2c7eb)

**Comment by clausmichele** [comment]
@annefou which image/env should be used here?

**Comment by annefou** [comment]
You should use `MOOC (Dask Testing)`

**Comment by jonas-eberle** [comment]
Thanks @annefou , I was instructed to use the `Cubes & Clouds` environment (@clausmichele). With The `MOOC (Dask Testing)` I need to select a kernel - I used the `eurodatacube21-pangeo` proposed as preferred kernel - is this correct (@Schpidi) ?. 

Now the visualization part stops with the error `AttributeError: module 'dask.dataframe.core' has no attribute 'DataFrame'`. 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[24], line 1
----> 1 clipped_date.hvplot.image(
      2     x='x',
      3     y='y',
      4     groupby='date',
      5     crs=pyproj.CRS.from_epsg(32632),
      6     cmap='Pastel2',
      7     clim=(-1, 2),
      8     frame_width=500,
      9     frame_height=500,
     10     title='Snowmap',
     11     geo=True, tiles='OSM')

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/hvplot/plotting/core.py:2067, in hvPlot.image(self, x, y, z, colorbar, **kwds)
   2015 def image(self, x=None, y=None, z=None, colorbar=True, **kwds):
   2016     """
   2017     Image plot
   2018 
   (...)
   2065     - Plotly: https://plotly.com/python/imshow/
   2066     """
-> 2067     return self(x, y, z=z, kind='image', colorbar=colorbar, **kwds)

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/hvplot/plotting/core.py:95, in hvPlotBase.__call__(self, x, y, kind, **kwds)
     92         plot = self._get_converter(x, y, kind, **kwds)(kind, x, y)
     93         return pn.panel(plot, **panel_dict)
---> 95 return self._get_converter(x, y, kind, **kwds)(kind, x, y)

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/hvplot/plotting/core.py:102, in hvPlotBase._get_converter(self, x, y, kind, **kwds)
    100 y = y or params.pop('y', None)
    101 kind = kind or params.pop('kind', None)
--> 102 return HoloViewsConverter(self._data, x, y, kind=kind, **params)

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/hvplot/converter.py:620, in HoloViewsConverter.__init__(self, data, x, y, kind, by, use_index, group_label, value_label, backlog, persist, use_dask, crs, fields, groupby, dynamic, grid, legend, rot, title, xlim, ylim, clim, robust, symmetric, logx, logy, loglog, hover, subplots, label, invert, stacked, colorbar, datashade, rasterize, downsample, resample_when, row, col, debug, framewise, aggregator, projection, global_extent, geo, precompute, flip_xaxis, flip_yaxis, dynspread, hover_cols, x_sampling, y_sampling, project, tools, attr_labels, coastline, tiles, tiles_opts, sort_date, check_symmetric_max, transforms, stream, cnorm, features, rescale_discrete_levels, autorange, **kwds)
    618 self.dynamic = dynamic
    619 self.geo = any([geo, crs, global_extent, projection, project, coastline, features])
--> 620 self.crs = self._process_crs(data, crs) if self.geo else None
    621 self.output_projection = self.crs
    622 self.project = project

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/hvplot/converter.py:953, in HoloViewsConverter._process_crs(self, data, crs)
    950     _crs = crs
    952 try:
--> 953     return process_crs(_crs)
    954 except ValueError as e:
    955     # only raise error if crs was specified in kwargs
    956     if crs:

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/hvplot/util.py:275, in process_crs(crs)
    273     missing.append('cartopy')
    274 try:
--> 275     import geoviews as gv  # noqa
    276 except ImportError:
    277     missing.append('geoviews')

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/geoviews/__init__.py:18
     16 from ._warnings import GeoviewsDeprecationWarning, GeoviewsUserWarning  # noqa: F401
     17 from . import data                                  # noqa (API import)
---> 18 from . import plotting                              # noqa (API import)
     19 from . import feature                               # noqa (API import)
     20 from . import tile_sources                          # noqa (API import)

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/geoviews/plotting/__init__.py:19
     17 backends = Store.loaded_backends()
     18 if 'bokeh' in backends:
---> 19     _load_bokeh()
     20 if 'matplotlib' in backends:
     21     _load_mpl()

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/geoviews/plotting/__init__.py:10, in _load_bokeh()
      9 def _load_bokeh():
---> 10     from . import bokeh

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/geoviews/plotting/bokeh/__init__.py:23
     17 from holoviews.plotting.bokeh.raster import RasterPlot, RGBPlot, QuadMeshPlot
     18 from ...element import (
     19     WMTS, Points, Polygons, Path, Contours, Shape, Image, ImageStack, Feature,
     20     Text, RGB, Nodes, EdgePaths, Graph, TriMesh, QuadMesh, VectorField,
     21     Labels, HexTiles, LineContours, FilledContours, Rectangles, Segments
     22 )
---> 23 from ...operation import (
     24     project_image, project_points, project_path, project_graph,
     25     project_quadmesh, project_geom, project_vectorfield
     26 )
     27 from ...tile_sources import _ATTRIBUTIONS
     28 from ...util import poly_types, line_types

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/geoviews/operation/__init__.py:15
     13 geo_ops = [contours, bivariate_kde]
     14 try:
---> 15     from holoviews.operation.datashader import shade, stack, dynspread
     16     from holoviews.operation.resample import ResampleOperation2D
     17     geo_ops += [ResampleOperation2D, shade, stack, dynspread]

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/holoviews/operation/datashader.py:6
      3 from functools import partial
      5 import dask.dataframe as dd
----> 6 import datashader as ds
      7 import datashader.reductions as rd
      8 import datashader.transfer_functions as tf

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/datashader/__init__.py:14
     12 from .pipeline import Pipeline                           # noqa (API import)
     13 from . import transfer_functions as tf                   # noqa (API import)
---> 14 from . import data_libraries                             # noqa (API import)
     16 # Make RaggedArray pandas extension array available for
     17 # pandas >= 0.24.0 is installed
     18 from pandas import __version__ as pandas_version

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/datashader/data_libraries/__init__.py:5
      3 try:
      4     import dask as _dask  # noqa (Test dask installed)
----> 5     from . import dask    # noqa (API import)
      6 except ImportError:
      7     pass

File /home/conda/eurodatacube21/d772adbc52f50a66774f887880029d80ca8be33a3158bd54c24da2a79f8afa82-20250210-121304-225405-546-pangeo/lib/python3.11/site-packages/datashader/data_libraries/dask.py:55
     51     return scheduler(dsk, name)
     54 # Classic Dask.DataFrame
---> 55 bypixel.pipeline.register(dd.core.DataFrame)(dask_pipeline)
     57 with suppress(ImportError):
     58     import dask_expr

AttributeError: module 'dask.dataframe.core' has no attribute 'DataFrame'
```

**Comment by annefou** [comment]
Ok. That is weird. Was the image rebuilt? The issue is that we do not use the Pangeo notebook image (that we test, etc.). I am not sure what is used here (in terms of versions for each package). Where can I find it?

**Comment by annefou** [comment]
@Schpidi, do you use https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/packages.txt to create the image? I understood from our last meeting that you added another package, which may have triggered an issue.
Could you let us know which environment you are using?

**Comment by Schpidi** [comment]
I believe when you tested you used the `eurodatacube21/pangeo` kernel right? This was built using this `environment.yml` today when I fixed `pystac=1.11.0`:

```yaml
channels:
- conda-forge
dependencies:
- adlfs=2024.4.1
- argopy=0.1.14
- awscli=2.15.62
- black=24.4.2
- boto3=1.34.106
- bottleneck=1.3.8
- cartopy=0.23.0
- cdsapi=0.7.0
- cfgrib=0.9.12.0
- cf_xarray=0.9.1
- ciso=0.2.0
- cmocean=4.0.3
- dask-ml=2024.3.20
- datashader=0.16.2
- descartes=1.1.0
- earthaccess=0.9.0
- eofs=1.4.1
- erddapy=2.2.0
- esmpy=8.6.1
- fastjmd95=0.2.1
- flox=0.9.8
- fsspec=2024.5.0
- gcm_filters=0.3.0
- gcsfs=2024.5.0
- gh=2.50.0
- gh-scoped-creds=4.1
- geocube=0.5.2
- geopandas=0.14.4
- geopy=2.4.1
- geoviews-core=1.12.0
- git-lfs=3.5.1
- gsw=3.6.18
- h5netcdf=1.3.0
- h5py=3.11.0
- holoviews=1.18.3
- hvplot=0.10.0
- intake=2.0.5
- intake-esm=2023.11.10
- intake-geopandas=0.4.0
- intake-stac=0.4.0
- intake-xarray=0.7.0
- ipdb=0.13.13
- ipykernel=6.29.3
- ipyleaflet=0.19.1
- ipympl=0.9.4
- ipytree=0.2.2
- ipywidgets=8.1.3
- jupyterlab_code_formatter=2.2.1
- jupyterlab-git=0.50.0
- jupyterlab-lsp=5.1.0
- jupyterlab-myst=2.4.2
- jupyter-panel-proxy=0.1.0
- jupyter-resource-usage=1.0.2
- kerchunk=0.2.5
- line_profiler=4.1.1
- lonboard=0.9.3
- lxml=5.2.2
- lz4=4.3.3
- matplotlib-base=3.8.4
- memory_profiler=0.61.0
- metpy=1.6.2
- nb_conda_kernels=2.5.1
- nbstripout=0.7.1
- nc-time-axis=1.4.1
- netcdf4=1.6.5
- numbagg=0.8.1
- numcodecs=0.12.1
- numpy=1.26.4
- numpy_groupies=0.11.1
- odc-stac=0.3.9
- pandas=2.2.2
- panel=1.4.4
- parcels=3.0.3
- param=2.1.0
- pop-tools=2023.6.0
- pyarrow=14.0.2
- pycamhd=0.7.0
- pydap=3.4.0
- pystac=1.11.0
- pystac-client=0.8.1
- python-blosc=1.11.1
- python-gist=0.10.6
- python-graphviz=0.20.3
- python-lsp-ruff=2.2.0
- python-xxhash=3.4.1
- rasterio=1.3.9
- rechunker=0.5.2
- rio-cogeo=5.3.0
- rioxarray=0.15.5
- ruff=0.4.7
- s3fs=2024.5.0
- satpy=0.48.0
- scikit-image=0.22.0
- scikit-learn=1.5.0
- scipy=1.13.1
- seaborn=0.13.2
- sparse=0.15.4
- snakeviz=2.2.0
- stackstac=0.5.0
- tiledb-py=0.26.0
- timezonefinder=6.4.1
- watermark=2.4.3
- xarray=2024.5.0
- xarrayutils=2.0.1
- xarray-datatree=0.0.14
- xarray_leaflet=0.2.3
- xarray-spatial=0.4.0
- xbatcher=0.3.0
- xcape=0.1.4
- xclim=0.49.0
- xesmf=0.8.5
- xgboost=2.0.3
- xgcm=0.8.1
- xhistogram=0.3.2
- xmip=0.7.2
- xmitgcm=0.5.2
- xpublish=0.3.3
- xrft=1.0.1
- xskillscore=0.0.26
- xxhash=0.8.2
- zarr=2.18.2
- rio-stac=0.10.1
description: ''
name: pangeo
prefix: null
```

The `cubes-and-clouds/pangeo` kernel was built on 2024-09-05 using:

```yaml
channels:
- conda-forge
dependencies:
- adlfs=2024.4.1
- argopy=0.1.14
- awscli=2.15.62
- black=24.4.2
- boto3=1.34.106
- bottleneck=1.3.8
- cartopy=0.23.0
- cdsapi=0.7.0
- cfgrib=0.9.12.0
- cf_xarray=0.9.1
- ciso=0.2.0
- cmocean=4.0.3
- dask-ml=2024.3.20
- datashader=0.16.2
- descartes=1.1.0
- earthaccess=0.9.0
- eofs=1.4.1
- erddapy=2.2.0
- esmpy=8.6.1
- fastjmd95=0.2.1
- flox=0.9.8
- fsspec=2024.5.0
- gcm_filters=0.3.0
- gcsfs=2024.5.0
- gh=2.50.0
- gh-scoped-creds=4.1
- geocube=0.5.2
- geopandas=0.14.4
- geopy=2.4.1
- geoviews-core=1.12.0
- git-lfs=3.5.1
- gsw=3.6.18
- h5netcdf=1.3.0
- h5py=3.11.0
- holoviews=1.18.3
- hvplot=0.10.0
- intake=2.0.5
- intake-esm=2023.11.10
- intake-geopandas=0.4.0
- intake-stac=0.4.0
- intake-xarray=0.7.0
- ipdb=0.13.13
- ipykernel=6.29.3
- ipyleaflet=0.19.1
- ipympl=0.9.4
- ipytree=0.2.2
- ipywidgets=8.1.3
- jupyterlab_code_formatter=2.2.1
- jupyterlab-git=0.50.0
- jupyterlab-lsp=5.1.0
- jupyterlab-myst=2.4.2
- jupyter-panel-proxy=0.1.0
- jupyter-resource-usage=1.0.2
- kerchunk=0.2.5
- line_profiler=4.1.1
- lonboard=0.9.3
- lxml=5.2.2
- lz4=4.3.3
- matplotlib-base=3.8.4
- memory_profiler=0.61.0
- metpy=1.6.2
- nb_conda_kernels=2.5.1
- nbstripout=0.7.1
- nc-time-axis=1.4.1
- netcdf4=1.6.5
- numbagg=0.8.1
- numcodecs=0.12.1
- numpy=1.26.4
- numpy_groupies=0.11.1
- odc-stac=0.3.9
- pandas=2.2.2
- panel=1.4.4
- parcels=3.0.3
- param=2.1.0
- pop-tools=2023.6.0
- pyarrow=14.0.2
- pycamhd=0.7.0
- pydap=3.4.0
- pystac=1.10.1
- pystac-client=0.8.1
- python-blosc=1.11.1
- python-gist=0.10.6
- python-graphviz=0.20.3
- python-lsp-ruff=2.2.0
- python-xxhash=3.4.1
- rasterio=1.3.9
- rechunker=0.5.2
- rio-cogeo=5.3.0
- rioxarray=0.15.5
- ruff=0.4.7
- s3fs=2024.5.0
- satpy=0.48.0
- scikit-image=0.22.0
- scikit-learn=1.5.0
- scipy=1.13.1
- seaborn=0.13.2
- sparse=0.15.4
- snakeviz=2.2.0
- stackstac=0.5.0
- tiledb-py=0.26.0
- timezonefinder=6.4.1
- watermark=2.4.3
- xarray=2024.5.0
- xarrayutils=2.0.1
- xarray-datatree=0.0.14
- xarray_leaflet=0.2.3
- xarray-spatial=0.4.0
- xbatcher=0.3.0
- xcape=0.1.4
- xclim=0.49.0
- xesmf=0.8.5
- xgboost=2.0.3
- xgcm=0.8.1
- xhistogram=0.3.2
- xmip=0.7.2
- xmitgcm=0.5.2
- xpublish=0.3.3
- xrft=1.0.1
- xskillscore=0.0.26
- xxhash=0.8.2
- zarr=2.18.2
- rio-stac=0.10.1
description: ''
name: pangeo
prefix: null
```

For completeness, there are also three other kernels available in the `cubes-and-clouds` env: `cubes_and_clouds`, `cubes_and_clouds2`, and `cubes_and_clouds-new`.
